version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./public/images:/app/public/images

  backend:
    build: ./backend
    ports:
      - "5328:5328"
    volumes:
      - ./public/images:/app/public/images
